### ISSUE TITLE
라우터에 async/await을 사용할 경우 UnhandledPromiseRejectionWarning이 발생합니다.

### ISSUE THREAD

**Issue by sdass12** [gingaminga/server-boilerplate#2]
라우터에서 async 함수를 호출했을 때 에러가 발생하면 핸들링이 안 됩니다.

참고 블로그 : https://programmingsummaries.tistory.com/399 
해결 방안 : https://www.npmjs.com/package/express-asyncify

**Comment by gingaminga** [comment]
무조건 try catch로 감싸서 처리하려 했는데.. 해당 방안 감사합니다
